CREATE TABLE "pg-drizzle_candidate_profile" (
	"user_id" text PRIMARY KEY NOT NULL,
	"githubLogin" varchar(255) NOT NULL,
	"github_url" text NOT NULL,
	"lastAnalyzedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_job" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_job_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"hr_user_id" text NOT NULL,
	"title" varchar(255) NOT NULL,
	"description" text,
	"required_stacks" jsonb NOT NULL,
	"match_threshold" integer NOT NULL,
	"is_published" boolean NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_job_match" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_job_match_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"job_id" integer NOT NULL,
	"candidate_user_id" text NOT NULL,
	"analysis_id" integer,
	"score" integer NOT NULL,
	"rationale" jsonb,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_repo_analysis" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_repo_analysis_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_user_id" text NOT NULL,
	"repo_full_name" text NOT NULL,
	"tech_stack" jsonb NOT NULL,
	"signals" jsonb,
	"rationale" jsonb,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_candidate_profile" ADD CONSTRAINT "pg-drizzle_candidate_profile_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_job" ADD CONSTRAINT "pg-drizzle_job_hr_user_id_user_id_fk" FOREIGN KEY ("hr_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_job_match" ADD CONSTRAINT "pg-drizzle_job_match_job_id_pg-drizzle_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."pg-drizzle_job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_job_match" ADD CONSTRAINT "pg-drizzle_job_match_candidate_user_id_user_id_fk" FOREIGN KEY ("candidate_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_job_match" ADD CONSTRAINT "pg-drizzle_job_match_analysis_id_pg-drizzle_repo_analysis_id_fk" FOREIGN KEY ("analysis_id") REFERENCES "public"."pg-drizzle_repo_analysis"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_repo_analysis" ADD CONSTRAINT "pg-drizzle_repo_analysis_candidate_user_id_user_id_fk" FOREIGN KEY ("candidate_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "job_match_job_idx" ON "pg-drizzle_job_match" USING btree ("job_id");--> statement-breakpoint
CREATE INDEX "job_match_candidate_idx" ON "pg-drizzle_job_match" USING btree ("candidate_user_id");--> statement-breakpoint
CREATE INDEX "job_match_analysis_idx" ON "pg-drizzle_job_match" USING btree ("analysis_id");--> statement-breakpoint
CREATE UNIQUE INDEX "job_match_unique" ON "pg-drizzle_job_match" USING btree ("job_id","candidate_user_id","analysis_id");