CREATE TYPE "public"."assessment_track" AS ENUM('specialist', 'expansion', 'pragmatist');--> statement-breakpoint
CREATE TABLE "pg-drizzle_assignment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"job_id" integer NOT NULL,
	"repo_template_url" text NOT NULL,
	"instructions" text,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_candidate_assignment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_candidate_assignment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"assignment_id" integer NOT NULL,
	"job_id" integer NOT NULL,
	"candidate_user_id" text NOT NULL,
	"repo_url" text,
	"submission_branch" text NOT NULL,
	"status" text NOT NULL,
	"decision_status" text NOT NULL,
	"todo" jsonb,
	"messages" jsonb,
	"timeline" jsonb,
	"capability_stats" jsonb,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_candidate_track_selection" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_candidate_track_selection_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"candidate_user_id" text NOT NULL,
	"analysis_id" integer NOT NULL,
	"track" "assessment_track" NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_candidate_profile" ADD COLUMN "preferred_culture" text;--> statement-breakpoint
ALTER TABLE "pg-drizzle_candidate_profile" ADD COLUMN "resume" jsonb;--> statement-breakpoint
ALTER TABLE "pg-drizzle_job" ADD COLUMN "role_type" text;--> statement-breakpoint
ALTER TABLE "pg-drizzle_job" ADD COLUMN "seniority" text;--> statement-breakpoint
ALTER TABLE "pg-drizzle_repo_analysis" ADD COLUMN "readme_excerpt" text;--> statement-breakpoint
ALTER TABLE "pg-drizzle_repo_analysis" ADD COLUMN "domain_tags" jsonb;--> statement-breakpoint
ALTER TABLE "pg-drizzle_assignment" ADD CONSTRAINT "pg-drizzle_assignment_job_id_pg-drizzle_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."pg-drizzle_job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_candidate_assignment" ADD CONSTRAINT "pg-drizzle_candidate_assignment_assignment_id_pg-drizzle_assignment_id_fk" FOREIGN KEY ("assignment_id") REFERENCES "public"."pg-drizzle_assignment"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_candidate_assignment" ADD CONSTRAINT "pg-drizzle_candidate_assignment_job_id_pg-drizzle_job_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."pg-drizzle_job"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_candidate_assignment" ADD CONSTRAINT "pg-drizzle_candidate_assignment_candidate_user_id_user_id_fk" FOREIGN KEY ("candidate_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_candidate_track_selection" ADD CONSTRAINT "pg-drizzle_candidate_track_selection_candidate_user_id_user_id_fk" FOREIGN KEY ("candidate_user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_candidate_track_selection" ADD CONSTRAINT "pg-drizzle_candidate_track_selection_analysis_id_pg-drizzle_repo_analysis_id_fk" FOREIGN KEY ("analysis_id") REFERENCES "public"."pg-drizzle_repo_analysis"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "candidate_assignment_candidate_idx" ON "pg-drizzle_candidate_assignment" USING btree ("candidate_user_id");--> statement-breakpoint
CREATE INDEX "candidate_assignment_job_idx" ON "pg-drizzle_candidate_assignment" USING btree ("job_id");--> statement-breakpoint
CREATE UNIQUE INDEX "candidate_assignment_unique" ON "pg-drizzle_candidate_assignment" USING btree ("assignment_id","candidate_user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "candidate_track_selection_unique" ON "pg-drizzle_candidate_track_selection" USING btree ("candidate_user_id","analysis_id");--> statement-breakpoint
CREATE INDEX "candidate_track_selection_candidate_idx" ON "pg-drizzle_candidate_track_selection" USING btree ("candidate_user_id");--> statement-breakpoint
CREATE INDEX "candidate_track_selection_analysis_idx" ON "pg-drizzle_candidate_track_selection" USING btree ("analysis_id");